### ISSUE TITLE
Examples on JavaScript Promises are broken

### ISSUE THREAD

**Issue by noelleleigh** [html5rocks/www.html5rocks.com#1459]
At least on https://developers.google.com/web/fundamentals/getting-started/primers/promises?hl=en#promisifying_xmlhttprequest
the links to examples (`story.json`) are broken.

**Comment by TheDartCode** [comment]
The one at https://developers.google.com/web/fundamentals/getting-started/primers/promises#bonus_round_promises_and_generators is broken, too.

The link is 
https://googlesamples.github.io/web-fundamentals/fundamentals/gettings-started/primers/async-generators-example.html
instead of
https://googlesamples.github.io/web-fundamentals/fundamentals/getting-started/primers/async-generators-example.html

**Comment by shogunsea** [comment]
the `story.json` seems still broken? 
![image](https://cloud.githubusercontent.com/assets/2238944/21288858/cb70619e-c453-11e6-99c4-5d5e85500ec5.png)

it links to a github page: https://github.com/googlesamples/web-fundamentals/blob/gh-pages/fundamentals/getting-started/primers/story.json
